name: workflow_test_with_go_prints
on: 
  push:
    branches:
      - main
      - master

jobs:
  build_and_run_go:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: go build
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.5

      - name: go tidy(Install dependencies)
        run: go mod tidy

      - name: go build
        run: go build
      
      - name: go run 
        run: go run .
