name: ci_cd_testing
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build_and_run_go:
    runs-on: ubuntu-latest

    steps:
      - name:  clone repo
        uses: actions/checkout@v4
      - name: go install
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.1"
      - name: go mod download
        run: go mod download
      - name: build go
        run: go build -o bin/go_code
      - name: run go
        run: ./bin/go_code
